import type { MobileHomeSummaryResponse, ShiftSummaryResponse, TaskSummaryResponse } from './mobile.types';

export const mobileShiftsMock: ShiftSummaryResponse = {
  store_id: localStorage.getItem('store_id') || 'STORE001',
  date: new Date().toISOString().slice(0, 10),
  shifts: [
    {
      shift_id: 'shift_001',
      shift_name: '午市班',
      shift_date: new Date().toISOString().slice(0, 10),
      start_time: '10:00',
      end_time: '14:00',
      position_name: '楼面主管',
      shift_status: 'upcoming',
      attendance_status: 'not_checked_in',
      related_task_count: 3,
      can_check_in: true,
      can_check_out: false,
    },
    {
      shift_id: 'shift_002',
      shift_name: '晚市班',
      shift_date: new Date().toISOString().slice(0, 10),
      start_time: '17:00',
      end_time: '21:30',
      position_name: '楼面主管',
      shift_status: 'upcoming',
      attendance_status: 'not_checked_in',
      related_task_count: 2,
      can_check_in: false,
      can_check_out: false,
    },
  ],
};

export const mobileTasksMock: TaskSummaryResponse = {
  store_id: localStorage.getItem('store_id') || 'STORE001',
  total: 4,
  pending_count: 2,
  expired_count: 1,
  tasks: [
    {
      task_id: 'task_001',
      task_title: '开市前巡检',
      task_type: 'inspection',
      priority: 'p1_high',
      task_status: 'pending',
      deadline_at: `${new Date().toISOString().slice(0, 10)}T10:30:00`,
      assignee_name: '李平',
      need_evidence: true,
      need_review: true,
    },
    {
      task_id: 'task_002',
      task_title: '午市备货确认',
      task_type: 'replenishment',
      priority: 'p2_medium',
      task_status: 'in_progress',
      deadline_at: `${new Date().toISOString().slice(0, 10)}T11:00:00`,
      assignee_name: '李平',
      need_evidence: false,
      need_review: false,
    },
    {
      task_id: 'task_003',
      task_title: '包厢服务复拍',
      task_type: 'service',
      priority: 'p2_medium',
      task_status: 'rejected',
      deadline_at: `${new Date().toISOString().slice(0, 10)}T15:00:00`,
      assignee_name: '李平',
      need_evidence: true,
      need_review: true,
    },
    {
      task_id: 'task_004',
      task_title: '催菜超时异常处置',
      task_type: 'incident_handle',
      priority: 'p0_urgent',
      task_status: 'expired',
      deadline_at: `${new Date().toISOString().slice(0, 10)}T09:40:00`,
      assignee_name: '李平',
      need_evidence: false,
      need_review: false,
    },
  ],
};

export const mobileHomeSummaryMock: MobileHomeSummaryResponse = {
  store_id: localStorage.getItem('store_id') || 'STORE001',
  as_of: new Date().toISOString(),
  role_name: '店长',
  unread_alerts_count: 2,
  pending_approvals_count: 1,
  today_revenue_yuan: 28650,
  food_cost_pct: 31.8,
  waiting_count: 7,
  health_score: 82,
  health_level: 'good',
  weakest_dimension: '成本率',
  today_shift: mobileShiftsMock.shifts[0],
  top_tasks: mobileTasksMock.tasks.slice(0, 3),
};
