apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: zhilian-os
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
